learning_templates/basicapp/urls.py
from django.conf.urls import url
from django.urls import path, include
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('other/', views.other, name = 'other'),
    path('relative/', views.relative, name = 'relative')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basicapp/', include('basicapp.urls')),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'basicapp/index.html')

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request, 'basicapp/relative_url_templates.html')
    

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class = "navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

        {% block body_block %}


        {% endblock %}
        <div class="jumbotron">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
   </div>


  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
  {% block body_block %}
      <h1>Index Page</h1>
  {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}
<h1>this is Other Page</h1>
{% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Relative Template Page</h1>
    <a href="{% url 'basicapp:other' %}">Other Page</a>
    <br>
    <a href="{% url 'admin:index' %}">Admin Page</a>
    <br>
    <a href="{% url 'index' %}">Index</a>
  </body>
</html>